pcrs/pcrs/urls.py
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import login
from users.views import UserSettingsView

admin.autodiscover()

urlpatterns = [
    url(r'^$', login.login_view, name='login'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^login/', login.login_view, name='login'),
    url(r'^logout$', login.logout_view, name = 'logout_view'),
    url(r'^settings$', UserSettingsView.as_view(), name = 'user_settings_view'),

    url(r'^sections/', (include('users.section_urls'))),
    url(r'^users/', (include('users.user_urls'))),
    url(r'^problems/', include('problems.urls')),
    url(r'^content/', include('content.urls')),
    url(r'^editor/', include('editor.urls')),
]

pcrs/problems/urls.py
from django.conf.urls import include, url
from pcrs.settings import INSTALLED_PROBLEM_APPS

pattern_options = {
    'problems_python': (r'^python/', 'problems_python.urls'),
    'problems_c': (r'^c/', 'problems_c.urls'),
    'problems_java': (r'^java/', 'problems_java.urls'),
    'problems_multiple_choice': (r'^multiple_choice/', 'problems_multiple_choice.urls'),
    'problems_r': (r'^r/', 'problems_r.urls'),
    'problems_rdb': (r'^rdb/', 'problems_rdb.urls'),
    'problems_sql': (r'^sql/', 'problems_sql.urls'),
    'problems_ra': (r'^ra/', 'problems_ra.urls'),
    'problems_timed': (r'^timed/', 'problems_timed.urls'),
    'problems_rating': (r'^rating/', 'problems_rating.urls'),
    'problems_short_answer': (r'^short_answer/', 'problems_short_answer.urls'),
    'problems_riscv': (r'^riscv/', 'problems_riscv.urls'),
    'problems_parsons': (r'^parsons/', 'problems_parsons.urls'),
}

# pattern_list = [''] + [url(pattern_options[pt][0], include(pattern_options[pt][1])) for pt in INSTALLED_PROBLEM_APPS.keys()]
pattern_list = [url(pattern_options[pt][0], include(pattern_options[pt][1]))
                for pt in INSTALLED_PROBLEM_APPS.keys()]

urlpatterns = [*pattern_list]

pcrs/problems_timed/urls.py
from django.conf.urls import url

from problems.views import (ProblemCreateView,
                            ProblemUpdateView, ProblemClearView,
                            ProblemDeleteView)
from problems_timed.models import Problem
from problems_timed.forms import ProblemForm
from problems_timed.views import (ProblemCreateRedirectView,
                                  PageCreateView, PagesCreateView,
                                  PageUpdateView, PageDeleteView,
                                  SubmissionView, ProblemListView)
from problems_timed.async_requests import AsyncAttempt, AsyncDownload

urlpatterns = [

    url(r'^list$',
        ProblemListView.as_view(model=Problem),
        name='timed_list'),

    url(r'^create$',
        ProblemCreateView.as_view(model=Problem, form_class=ProblemForm),
        name='timed_create'),

    url(r'^create_redirect$',
        ProblemCreateRedirectView.as_view(model=Problem, form_class=ProblemForm),
        name='timed_create_redirect'),

    url(r'^(?P<pk>[0-9]+)/?$',
        ProblemUpdateView.as_view(model=Problem, form_class=ProblemForm,
        template_name='problems_timed/problem_form.html'),
        name='timed_update'),

    url(r'^(?P<pk>[0-9]+)/clear$',
        ProblemClearView.as_view(model=Problem),
        name='timed_clear'),

    url(r'^(?P<pk>[0-9]+)/delete$',
        ProblemDeleteView.as_view(model=Problem),
        name='timed_delete'),

    url(r'^(?P<problem>[0-9]+)/page$',
        PageCreateView.as_view(),
        name='timed_add_page'),

    url(r'^(?P<problem>[0-9]+)/pages$',
        PagesCreateView.as_view(),
        name='timed_add_pages'),

    url(r'^(?P<problem>[0-9]+)/page/(?P<pk>[0-9]+)/?$',
        PageUpdateView.as_view(),
        name='timed_update_page'),

    url(r'^(?P<problem>[0-9]+)/page/(?P<pk>[0-9]+)/delete$',
        PageDeleteView.as_view(),
        name='timed_delete_page'),

    url(r'^(?P<problem>[0-9]+)/submit$',
        SubmissionView.as_view(),
        name='timed_submit'),

    url(r'^(?P<problem_pk>[0-9]+)/attempt$',
        AsyncAttempt.problem_attempt,
        name='attempt'),

    url(r'^(?P<problem_pk>[0-9]+)/download$',
        AsyncDownload.download_submissions,
        name='download'),

]

pcrs/problems_timed/models.py
from django.db import models
from django.utils import timezone

from pcrs.models import AbstractSelfAwareModel
from problems.models import AbstractProblem, AbstractSubmission
from users.models import PCRSUser, Section


class Problem(AbstractProblem):
    """
    A timed problem.
    """
    
    name = models.CharField(max_length=150)
    problem_description = models.TextField(blank=True)
    submission_description = models.TextField(blank=True)
    delay = models.PositiveIntegerField(default=5)
    attempts = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.name

    def prepareJSON(self):
        """
        Returns serializatin of problem and its pages set in JSON format.
        """
        content = [self]+[p for p in self.page_set.all()]
        return content

class Page(AbstractSelfAwareModel):
    """
    A timed problem page.
    """
    class Meta:
        ordering = ['id']
    
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    term_list = models.TextField(blank=True)
    
    def __str__(self):
        return self.term_list
    
    def get_absolute_url(self):
        return '{problem}/page/{pk}'.format(
            problem=self.problem.get_absolute_url(), pk=self.pk)
    
    def clean_text(self):
        self.text = self.text.replace('"', "'")
    
    def save(self, *args, **kwargs):
        self.clean_text()
        super(Page, self).save(*args, **kwargs)

class Submission(AbstractSubmission):
    """
    A timed problem submission.
    """
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    attempt = models.PositiveIntegerField(null=True)
    
    timestamp_complete = models.DateTimeField(null=True)
    score_max = models.SmallIntegerField(null=True)
    percent = models.DecimalField(max_digits=5, decimal_places=4, null=True)
    
    # allowing use of null=True as it indicates that the submission was not completed
    terms_list_problem = models.TextField(null=True)
    terms_list_student = models.TextField(null=True)
    terms_match = models.TextField(null=True)
    terms_miss = models.TextField(null=True)
    
    def set_best_submission(self):
        # from AbstractSubmission.set_best_submission()
        # modified to set best submission based on percent
        try:
            current_best = self.__class__.objects.get(
                user=self.user, problem=self.problem, has_best_score=True)
            if self.percent >= current_best.percent and self.pk != current_best.pk:
                current_best.has_best_score = False
                current_best.save()
                self.has_best_score = True
        except self.__class__.DoesNotExist:
            self.has_best_score = True
        finally:
            self.save()
    
    def set_score(self, submission_text):
        self.timestamp_complete = timezone.now()
        
        count, total, index = 0, 0, 0
        problem_list, match_list, miss_list = [], [], []
        student_list = submission_text.splitlines()
        
        for term in student_list:
            student_list[index] = term.strip().lower()
            index += 1
        
        for page in self.problem.page_set.all() :
            if page.term_list:
                problem_list += page.term_list.split(",")
        for term in problem_list:
            problem_list[total] = term.strip().lower()
            total += 1
        
        self.terms_list_problem = str(problem_list)
        self.terms_list_student = str(student_list)
        
        for term in problem_list:
            if term in student_list:
                match_list.append(term)
                count += 1
            else:
                miss_list.append(term)
        
        self.terms_match = str(match_list)
        self.terms_miss = str(miss_list)
        
        self.submission = submission_text
        self.score_max = total
        self.score = count
        
        self.percent = 0
        if total != 0:
            self.percent = count/total
        
        self.save()
        self.set_best_submission()

pcrs/problems_timed/forms.py
from crispy_forms.layout import ButtonHolder, Submit, Layout, Fieldset, Div, Button
from django import forms

from pcrs.form_mixins import BaseRelatedObjectForm, CrispyFormMixin
from problems.forms import BaseProblemForm, BaseSubmissionForm
from problems_timed.models import Problem, Page, Submission


class ProblemForm(forms.ModelForm, BaseProblemForm):
    
    class Meta:
        model = Problem
        fields = ('name', 'problem_description', 'submission_description', 'delay', 'attempts', 'author', 'tags', 'visibility')

    def __init__(self, *args, **kwargs):
        self.save_and_add = Submit('submit', 'Save and Add Pages',
                               css_class='btn-success pull-right',
                               formaction='create_redirect')
        
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        BaseProblemForm.__init__(self)
        
        if self.instance.pk:
            self.buttons = (Div(CrispyFormMixin.delete_button,
                                self.clear_button,
                                css_class='btn-group'),
                            Div(self.save_button,
                                css_class='btn-group pull-right'))
        self.helper.layout = Layout(Fieldset('', *self.Meta.fields),
                                    ButtonHolder(*self.buttons))

class PageForm(BaseRelatedObjectForm):
    class Meta:
        model = Page
        widgets = {'problem': forms.HiddenInput, 'term_list': forms.TextInput}
        fields = ('text', 'term_list', 'problem')

    def __init__(self, *args, **kwargs):
        BaseRelatedObjectForm.__init__(self, *args, formaction='pages',
                                       **kwargs)

class SubmissionForm(BaseSubmissionForm):
    submission = forms.CharField(widget=forms.Textarea())
    
    def __init__(self, *args, **kwargs):
        problem = kwargs.get('problem', None)
        super().__init__(*args, **kwargs)
        self.helper.layout = Layout(
            Fieldset('', 'submission'),
            ButtonHolder(self.submit_button, css_class='pull-right'))

pcrs/problems_timed/views.py
import json
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.views.generic import (CreateView, UpdateView, DeleteView, FormView)
from django.views.generic.detail import SingleObjectMixin

from problems_timed.models import Problem, Page, Submission
from problems_timed.forms import PageForm, SubmissionForm

from problems.views import ProblemListView, TestCaseView, SubmissionView, SubmissionViewMixin
from pcrs.generic_views import GenericItemCreateView

from users.views import UserViewMixin
from users.views_mixins import ProtectedViewMixin, CourseStaffViewMixin
from users.section_views import SectionViewMixin

class ProblemListView(ProblemListView):
    template_name = 'problems_timed/problem_list.html'

class ProblemCreateRedirectView(CourseStaffViewMixin, CreateView):
    model = Problem

    def get_success_url(self):
        return reverse('timed_add_page',
                       kwargs={'problem': self.object.pk})

class PageView(TestCaseView):
    model = Page
    form_class = PageForm
    template_name = 'problems_timed/page_form.html'
    object = None

    def get_success_url(self):
        return reverse('timed_add_page',
                       kwargs={'problem': self.object.problem.pk})

class PageCreateView(PageView, GenericItemCreateView):

    def get_success_url(self):
        return reverse('timed_update',
                       kwargs={'pk': self.object.problem.pk})

class PagesCreateView(PageView, GenericItemCreateView):
    pass

class PageUpdateView(PageView, UpdateView):
    template_name = 'problems_timed/page_update.html'

    def get_success_url(self):
        return reverse('timed_update',
                       kwargs={'pk': self.object.problem.pk})

class PageDeleteView(PageView, DeleteView):
    template_name = 'problems_timed/page_delete.html'

    def get_success_url(self):
        return reverse('timed_update',
                       kwargs={'pk': self.kwargs.get('problem')})

class SubmissionViewMixinTimed(SubmissionViewMixin, FormView):
    model = Submission
    form_class = SubmissionForm
    template_name = 'problems_timed/submission.html'

    def record_submission(self, request):
        user = request.user
        section = request.user.section
        problem = self.get_problem()
        self.submission = Submission.objects.filter(user=user, section=section, problem=problem).order_by('-pk')[:1][0]
        if self.submission.timestamp_complete:
            return HttpResponseForbidden()
        self.submission.set_score(request.POST['submission'])
        return []

class SubmissionView(ProtectedViewMixin, SubmissionViewMixinTimed,
                     SingleObjectMixin, UserViewMixin):
    form_class = SubmissionForm
    object = None

    def get_success_url(self):
        return reverse('timed_list')

    def get_request_info(self, request):
        info = {'user': request.user, 'section': request.user.section, 'problem': self.get_problem()}
        return info

    def get(self, request, *args, **kwargs):
        info = self.get_request_info(request)
        total = Submission.objects.filter(user=info['user'], section=info['section'], problem=info['problem']).count()

        show_button = 1
        if total >= info['problem'].attempts:
            show_button = 0

        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(form=form)
        context['show_button'] = show_button
        context['total_submissions'] = total
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.get_form_class())
        info = self.get_request_info(request)
        submission = Submission.objects.filter(user=info['user'], section=info['section'], problem=info['problem']).order_by('-pk')[:1][0]

        if submission.timestamp_complete:
            return HttpResponseForbidden()

        submission.set_score(request.POST['submission'])

        return HttpResponseRedirect('/content/quests')

pcrs/problems_timed/templates/problems_timed/download.html
<a id="download_button" class="pull-right" title="Download Submissions" href="{{ object.get_absolute_url }}/download">
    <i class="glyphicon glyphicon-save"></i>
</a>

pcrs/problems_timed/templates/problems_timed/html_reference.html
<div class="panel panel-default">
    <div class="panel-body">
        <div style="float: left">
            <u>Bolded text:</u><br>
            &lt;b&gt;<b>text here</b>&lt;/b&gt;<br><br>
            <u>Italicized text:</u><br>
            &lt;i&gt;<i>text here</i>&lt;/i&gt;<br><br>
            <u>Underlined text:</u><br>
            &lt;u&gt;<u>text here</u>&lt;/u&gt;<br><br>
            <u>Crossed out text:</u><br>
            &lt;del&gt;<del>text here</del>&lt;/del&gt;<br><br>
        </div>

        <div style="float: right">
            <u>Modify the size and/or color of text:</u><br>
            &lt;font size=&#39;<u>24</u>&#39; color=&#39;<u>red</u>&#39;&gt;<i>text here</i>&lt;/font&gt;<br><br>
            <u>Insert image:</u><br>
            &lt;img src=&#39;<u>url-to-image</u>&#39;&gt;<br><br>
            <u>Insert image and set size:</u><br>
            &lt;img src=&#39;<u>url-to-image</u>&#39; width=&#39;<u>560</u>&#39;
            height=&#39;<u>315</u>&#39;&gt;<br><br>
            <u>Insert YouTube video:</u><br>
            <i>* While at a video, click on "share" then "embed", and copy the code given. For example:</i><br>
            &lt;iframe width=&#39;<u>560</u>&#39; height=&#39;<u>315</u>&#39;
            src=&#39;<u>url-to-video</u>&#39; frameborder=&#39;<u>0</u>&#39;
            allowfullscreen&gt;&lt;/iframe&gt;<br>
        </div>

    </div>
</div>

pcrs/problems_timed/templates/problems_timed/js_page_iterator.html
<script type='text/javascript'>

    $(document).ready( function() {
        
        $('#submission_block, #page_container, #next_block, hr').toggle();
        $('#info_hr').toggle();
        
        var pages = [];
        {% for page in problem.page_set.all %}
            pages.push("<h1>{{ page.text | safe | linebreaksbr }}</h1>");
        {% endfor %}
        
        preloadImages(pages);
        
        var counter = 0;
        var delay = parseInt({{ problem.delay }}) * 1000;
        var container = document.getElementById('page_container');
        var intervalId = null;
        
        if ({{ show_button }} == 0) {
            $('#start_problem').prop('disabled', true);
        }
        
        $('#start_problem').click( function() {
            
            $.post(root + '/problems/timed/' + String({{ problem.pk }}) + '/attempt')
            .fail( function() {
                window.location.replace('/content/quests');
            });
            
            $('#start_problem, #links_block, #info_block, #show_attempts, #extra_br').fadeOut();
            
            setTimeout( function() {
                
                if (delay) {
                    timeIterator(counter, delay, container, pages, intervalId);
                } else {
                    stepIterator(counter, delay, container, pages, intervalId);
                }
                
            }, 2000);
            
        });
        
    });
    
</script>

pcrs/problems_timed/templates/problems_timed/page_delete.html
{% extends "pcrs/check_delete.html" %}

{% block alerts %}
        <div class="alert alert-danger">
            Note: Scores for existing submissions are <b>not</b> recalculated.
        </div>
{% endblock %}

pcrs/problems_timed/templates/problems_timed/page_form.html
{% extends "pcrs/crispy_form.html" %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $( document ).ready( function() {
            $( "#id_text" ).focus();
            
            $("#tags_toggle").click( function() {
                $("#tags_down, #tags_up").toggle();
                $("#tags_reference").slideToggle("slow");
            });
        });
    </script>
{% endblock %}

{% if object %}
    {% block page_title %}
        Edit Page
    {% endblock %}
{% endif %}

{% block links %}
    <a class="button" href="{{ problem.get_absolute_url }}">< Back to problem</a>
{% endblock %}

{% block content %}
    {% with object_list=problem.page_set.all list_name='Existing Pages' %}
        {% include "pcrs/related_items_list.html" %}
        <hr>
    {% endwith %}
    <div id="tags_toggle" style="text-align:right;cursor:pointer">
        <span id="tags_down" class="glyphicon glyphicon-chevron-down" style="vertical-align:middle"></span>
        <span id="tags_up" class="glyphicon glyphicon-chevron-up" style="vertical-align:middle;display:none"></span>
        HTML Tags Reference
    </div>
    <div id="tags_reference" style="margin-left:auto; margin-right:0;width:850px;display:none">
        {% include "problems_timed/html_reference.html" %}
    </div>
    {{ block.super }}
{% endblock %}

pcrs/problems_timed/templates/problems_timed/page_update.html
{% extends "problems_timed/page_form.html" %}

{% block content %}
    {{ block.super }}
    <!--{% include "pcrs/buttons/delete.html" %}-->
{% endblock %}

pcrs/problems_timed/templates/problems_timed/problem_form.html
{% extends "problems/problem_form.html" %}

{% block related_items %}
    {% if object %}
        {% with list_name='List of Pages' object_list=object.page_set.all related_item_name='page' %}
            {% include "pcrs/related_items.html" %}
        {% endwith %}
    {% endif %}
{% endblock %}

pcrs/problems_timed/templates/problems_timed/problem_list.html
{% extends "problems/problem_list.html" %}

{% block stylesheets %}
    {{ block.super }}
    <style>
        #download_button {
            margin-right: 25px;
        }
    </style>
{% endblock %}

{% block item_controls %}
    {{ block.super }}
    {% include "problems_timed/download.html" %}
{% endblock %}

pcrs/problems_timed/templates/problems_timed/submission.html
{% extends "problems/submission.html" %}

{% block page_title %}{% endblock %}

{% block scripts %}
    {{ block.super }}
    {% load static %}
    {% include "problems_timed/js_page_iterator.html" %}
    <script src="{% static "problems_timed/js/iterator_helpers.js" %}" type="text/javascript"></script>
    <script src="{% static "problems_timed/js/preload_images.js" %}" type="text/javascript"></script>
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    {% load static %}
    <link rel="stylesheet" href="{% static "problems_timed/css/submission_style.css" %}">
{% endblock %}

{% block content %}
    <div id="top_block">
        <div id="next_block">
                <span id="next_button" class="glyphicon glyphicon-arrow-right"></span>
        </div>

        <div id="show_attempts">
            Attempts: {{ total_submissions }} of {{ problem.attempts }}
        </div>
    </div>

    <br id="extra_br">

    <div id="info_block">
        <span id="problem_name">{{ problem.name }}</span>
        <hr id="info_hr" style="">
        {% if problem.problem_description %}
            {{ problem.problem_description | linebreaksbr }}
        {% else %}
            Press start to begin.
        {% endif %}
    </div>

    <br id="extra_br">

    <div align="center">
        {% if total_submissions >= problem.attempts %}
            <i>No attempts remaining.</i>
            <br>
        {% endif %}
        <button id="start_problem" class="btn btn-default" type="button">
            Start
        </button>
    </div>

        <div id="page_container"></div>

    <div id="submission_block">

        <div id="info_submission">
            {% if problem.submission_description %}
                {{ problem.submission_description | linebreaksbr }}
            {% else %}
                Enter each term on a separate line.
            {% endif %}
        </div>
        <br><br>
        {% load crispy_forms_tags %}
        {% crispy form %}
        {% load filters %}
    </div>

{% endblock %}