pcrs/pcrs/urls.py
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import login
from users.views import UserSettingsView

admin.autodiscover()

urlpatterns = [
    url(r'^$', login.login_view, name='login'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^login/', login.login_view, name='login'),
    url(r'^logout$', login.logout_view, name = 'logout_view'),
    url(r'^settings$', UserSettingsView.as_view(), name = 'user_settings_view'),

    url(r'^sections/', (include('users.section_urls'))),
    url(r'^users/', (include('users.user_urls'))),
    url(r'^problems/', include('problems.urls')),
    url(r'^content/', include('content.urls')),
    url(r'^editor/', include('editor.urls')),
]

pcrs/problems/urls.py
from django.conf.urls import include, url
from pcrs.settings import INSTALLED_PROBLEM_APPS

pattern_options = {
    'problems_python': (r'^python/', 'problems_python.urls'),
    'problems_c': (r'^c/', 'problems_c.urls'),
    'problems_java': (r'^java/', 'problems_java.urls'),
    'problems_multiple_choice': (r'^multiple_choice/', 'problems_multiple_choice.urls'),
    'problems_r': (r'^r/', 'problems_r.urls'),
    'problems_rdb': (r'^rdb/', 'problems_rdb.urls'),
    'problems_sql': (r'^sql/', 'problems_sql.urls'),
    'problems_ra': (r'^ra/', 'problems_ra.urls'),
    'problems_timed': (r'^timed/', 'problems_timed.urls'),
    'problems_rating': (r'^rating/', 'problems_rating.urls'),
    'problems_short_answer': (r'^short_answer/', 'problems_short_answer.urls'),
    'problems_riscv': (r'^riscv/', 'problems_riscv.urls'),
    'problems_parsons': (r'^parsons/', 'problems_parsons.urls'),
}

# pattern_list = [''] + [url(pattern_options[pt][0], include(pattern_options[pt][1])) for pt in INSTALLED_PROBLEM_APPS.keys()]
pattern_list = [url(pattern_options[pt][0], include(pattern_options[pt][1]))
                for pt in INSTALLED_PROBLEM_APPS.keys()]

urlpatterns = [*pattern_list]

pcrs/problems_java/urls.py
from django.conf.urls import url

from problems.views import *
from problems.st_async_requests import visualizer_details

from .forms import ProblemForm
from .models import Problem, Submission

from editor.views import EditorAsyncView


urlpatterns = [
    url(r'^list$',
        ProblemListView.as_view(model=Problem),
        name='coding_problem_list'),

    # Using C forms since they support the tag editor
    url(r'^create$',
        ProblemCreateView.as_view(model=Problem, form_class=ProblemForm,
                                  template_name='problems_java/problem_form.html'),
        name='coding_problem_create'),
    url(r'^(?P<pk>[0-9]+)/clone$',
        ProblemCloneView.as_view(model=Problem, form_class=ProblemForm,
                                 template_name='problems_java/problem_form.html'),
        name='code_problem_clone'),
    url(r'^create_and_add_testcase$',
        ProblemCreateAndAddTCView.as_view(model=Problem, form_class=ProblemForm),
        name='coding_problem_create_and_add_testcase'),
    url(r'^(?P<pk>[0-9]+)/?$',
        ProblemUpdateView.as_view(model=Problem, form_class=ProblemForm,
                                  template_name='problems_java/problem_form.html'),
        name='coding_problem_update'),
    url(r'^(?P<pk>[0-9]+)/clear$',
        ProblemClearView.as_view(model=Problem),
        name='coding_problem_clear'),
    url(r'^(?P<pk>[0-9]+)/delete$',
        ProblemDeleteView.as_view(model=Problem),
        name='coding_problem_delete'),
    url(r'^(?P<problem>[0-9]+)/submit$',
        SubmissionView.as_view(model=Submission,
                               template_name='problems_java/submission.html'),
        name='coding_problem_submit'),
    url(r'^(?P<problem>[0-9]+)/run$',
        SubmissionAsyncView.as_view(model=Submission),
        name='coding_problem_async_submit'),
    url(r'^editor/run$',
        EditorAsyncView.as_view(model=Submission, pType='java'),
        name='editor_problem_async_submit'),
    url(r'^(?P<problem>[0-9]+)/history$',
        SubmissionHistoryAsyncView.as_view(model=Submission),
        name='coding_problem_async_history'),

    url(r'^visualizer-details$', visualizer_details, name='visualizer details'),

    # monitoring
    url(r'^(?P<pk>[0-9]+)/monitor$',
        MonitoringView.as_view(model=Problem),
        name='coding_problem_monitor'),
    url(r'^(?P<pk>[0-9]+)/monitor_data$',
        MonitoringAsyncView.as_view(model=Problem),
        name='coding_problem_get_monitor_data'),

    url(r'^(?P<pk>[0-9]+)/browse_submissions$',
        BrowseSubmissionsView.as_view(model=Problem),
        name='coding_problem_browse_submissions'),
]

pcrs/problems_java/models.py
import re
import html

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_delete

from problems.pcrs_languages import GenericLanguage
from problems.models import (AbstractProgrammingProblem, AbstractSubmission,
    SubmissionPreprocessorMixin, AbstractSelfAwareModel,
    AbstractTestCaseWithDescription, AbstractTestRun, problem_delete)
from .java_language import CompilationError

test_suite_template = """import org.junit.*;
import static org.junit.Assert.*;

public class Tests {
    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    // <public test case description goes here>
    @Test
    public void test() {
    }
}
"""
visualizer_code_template = """public class Visualize {
    public static void main(String[] args) {
        // Code here will be executed in the visualizer
    }
}
"""

class Problem(AbstractProgrammingProblem):
    """
    A coding problem.

    A coding problem has all the properties of a problem, and
    a language and starter code
    """
    test_suite = models.TextField(blank=True,
        default=test_suite_template)
    visualizer_code = models.TextField(blank=True,
        default=visualizer_code_template)
    language = models.CharField(max_length=50,
                                choices=(('java', 'Java'),),
                                default='java')

    def __init__(self, *args, **kwargs):
        super(AbstractProgrammingProblem, self).__init__(*args, **kwargs)

        '''
        If the test suite is sent from a kwarg, we still want the
        test cases to regenerate when this problem is saved.
        _initial_test_suite _must_ differ from test_suite to make an update.
        '''
        if kwargs.get('test_suite'):
            self._initial_test_suite = test_suite_template
        else:
            self._initial_test_suite = self.test_suite

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude)

        # CodeMirror inserts carriage returns, but we don't like them!
        carriageReturnRegex = re.compile('\r')
        self.test_suite = re.sub(carriageReturnRegex, '', self.test_suite)
        self.solution = re.sub(carriageReturnRegex, '', self.solution)
        self.starter_code = re.sub(carriageReturnRegex, '', self.starter_code)
        self.visualizer_code = re.sub(carriageReturnRegex, '',
            self.visualizer_code)

        if self.starter_code == '':
            raise ValidationError({'starter_code': [
                'Invalid starter code',
            ]})

        if self.pk:
            if self.submission_set.all() and self._testSuiteHasChanged():
                raise ValidationError({'test_suite': [
                    'Submissions must be cleared before editing a testcase.',
                ]})

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        # In the editor, we don't save testcases
        if not self.is_editor_problem():
            # We need the problem to exist before generating test cases
            if not self.pk:
                super().save(force_insert, force_update, using, update_fields)

            '''
            We have to generate the test case table whenever we save a problem.
            It seems a bit hacky to do this, but most of PCRS depends on
            problems having a dedicated test case table.
            '''
            self._repopulateTestCaseTable()
            self.max_score = len(self.testcase_set.all())
        super().save(force_insert, force_update, using, update_fields)

    def _repopulateTestCaseTable(self):
        # Regenerate the test case table entries for this problem's test_suite
        testCaseInfo = self._generateTestInfo(self.test_suite)

        for testcase in self.testcase_set.all():
            testcase.delete()
        for test in testCaseInfo:
            self.testcase_set.create(
                test_name=test['name'],
                description=test['description'])

    def _testSuiteHasChanged(self):
        ''''Determines if the problem submission resulted in changed test code.
        This will ignore comments/descriptions and superfluous whitespace.
        NOTE: The current limitation is assertion messages. At some point
              it would be nice to ignore assert messages.

        Returns:
            True if the test code has changed, otherwise False.
        '''
        newSuiteCode = self._compressSuperfluousCode(self.test_suite)
        oldSuiteCode = self._compressSuperfluousCode(self._initial_test_suite)
        return newSuiteCode != oldSuiteCode

    def _compressSuperfluousCode(self, code):
        '''Can be used to compare two pieces of code.

        This will strip whitespace and most comments

        Args:
            code: String to strip from.
        Returns:
            A string, stripped of comments and whitespace (except newlines)
        '''
        # Remove (most) line comments
        code = re.sub(re.compile('\n[ \t]*\/\/[^\n]*'), '', code)
        # Remove (most) block comments
        code = re.sub(re.compile('\n[ \t]*\/\*.*?\*\/', re.DOTALL), '', code)
        # Compress irrelevant whitespace
        code = re.sub(re.compile('(?<=\n)[ \t\n]+', re.DOTALL), '', code)

        return code

    def _generateTestInfo(self, test_code):
        reg = re.compile(
            # Comment / Description capturing
            '(\/\/[^\n]*|\/\*+'        # Line comments & block comment starts
            '(?:.|\n[\t ]*\*[\t ]+)*?' # Block comment content
            '\n[\t ]*\*+\/)?[\t ]*\n'  # Block comment endings
            # Only capture methods annotated with @Test
            '[\t ]*@Test(?:\(.*?\))?\s*'
            # Capture method name
            'public\s*void\s*([\w_]+)'
        )
        return [
            {
                'name': m[1],
                'description': self._stripComment(m[0]),
            }
            for m in re.findall(reg, test_code)
        ]

    def _stripComment(self, comment):
        ''''Determines if the problem submission resulted in changed test code.
        This will ignore comments/descriptions and superfluous whitespace.
        NOTE: The current limitation is assertion messages. At some point
              it would be nice to ignore assert messages.

        Returns:
            True if the test code has changed, otherwise False.
        '''
        comment = re.sub('[\t ]*\/\/[\t ]*', '', comment)
        comment = re.sub('\/\*+', '', comment)
        comment = re.sub('\*+\/', '', comment)
        comment = re.sub('\n[\t ]*\*[\t ]*', '\n', comment)
        return comment.strip()


class Submission(SubmissionPreprocessorMixin, AbstractSubmission):
    """
    A coding problem submission.
    """
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def run_testcases(self, request, save=True):
        """
        Run all testcases for the submission and create testrun objects.
        Return the list of testrun results.
        """

        runner = GenericLanguage(self.problem.language)
        files = self.preprocessTags()

        try:
            # necessary since language requires compilation
            runner.lang.compile(self.user.username, files, self.problem.test_suite)
            test_results = runner.lang.run_test_suite()
        except CompilationError as e:
            return self._createErrorResponse(e, "Compile")
        except UnicodeEncodeError as e:
            return self._createErrorResponse(e)

        if 'exception' in test_results:
            return [{ 'passed_test': False,
                      'exception_type': 'error',
                      'exception': test_results['exception'],
                      'test_val': test_results['exception']}], None

        results = []
        for testcase in self.problem.testcase_set.all():
            test_name = testcase.test_name
            description = testcase.description
            description = html.escape(description) if description else '(hidden)'
            res = {
                'passed_test': True,
                'test_desc': description,
                #'debug': self.problem.isTestVisible(test_name)
                'debug': False, # Always false until debugger is implemented
                #'exception_type': 'error', (none initially)
                #'runtime_error': 'error message',
                'test_val': '',
            }
            failures = test_results['failures']
            if test_name in failures:
                message = self._formatTextForHTML(failures[test_name])
                res['test_val'] = message if len(message.strip()) > 0 else '(hidden)'
                res['passed_test'] = False
            if save:
                TestRun.objects.create(submission=self, testcase=testcase,
                    test_passed=res['passed_test'])
            results.append(res)

        runner.lang.clear() # Removing compiled files
        return results, None

    def _formatTextForHTML(self, text):
        return str(html.escape(text)).replace('\n', '<br />')

    def _createErrorResponse(self, e, errorLabel='Submission'):
        error = '{} Error:<br />{}'.format(errorLabel, str(e).replace('\n', '<br />'))
        return [{'passed_test': False,
                 'exception_type': 'error',
                 'exception': error,
                 'test_val': error}], None


class TestCase(AbstractTestCaseWithDescription):
    """
    A coding problem testcase.

    Visibility of test case information is controlled by is_visible.
    These test cases are generated when setting the problem test_suite.
    """
    problem = models.ForeignKey(Problem,
        on_delete=models.CASCADE, null=False, blank=False)
    test_name = models.TextField()

    def __str__(self):
        if self.description:
            return '{0}: {1}'.format(self.test_name, self.description)
        else:
            return self.test_name

pcrs/problems_java/forms.py
from django import forms
from crispy_forms.layout import HTML

from pcrs.form_mixins import BaseRelatedObjectForm
from problems.forms import BaseProblemForm
from .models import Problem


class ProblemForm(forms.ModelForm, BaseProblemForm):
    class Meta:
        model = Problem
        fields = ('name', 'description', 'starter_code', 'solution',
                  'test_suite', 'visualizer_code', 'author', 'tags', 'visibility')

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        BaseProblemForm.__init__(self)

        self.fields['starter_code'].initial = '[file NewFile.java]\n\n[/file]'
        self.fields['solution'].label += ' (optional)'
        self.fields['visualizer_code'].label += ' (optional)'

pcrs/problems_java/views.py
from editor.views import EditorView
from .models import *

class JavaEditorVisualizeView(EditorView):
    """
    View a given submission in the visualizer
    """
    def get_form_kwargs(self):
        submission = Submission.objects.get(pk=self.kwargs['pk'])

        code = submission.fuseStudentCodeIntoStarterCode()
        code = submission.removeTags(code)

        # Tack on the visualize file code.
        code = (
            '[file Visualize.java]\n'
            + submission.problem.visualizer_code + '\n'
            '[/file]\n'
            + code
        )

        kwargs = super().get_form_kwargs()
        kwargs['initial_code'] = code
        return kwargs

pcrs/problems_java/templates/problems_java/code_trace.html
<div class="pcrs-modal-trace" id="visualizerModal" aria-hidden="true">
    <div class="pcrs-modal-trace-content">
        <div class="pcrs-modal-body">
                <div id="visualize-code">

	            </div>
        </div>
        <div class="pcrs-modal-footer">
            <button type="button" class="reg-button" data-dismiss="modal">Close</button>
            <div><font size="1"><i>Visualization courtesy <a href="http://www.pythontutor.com/">Phil Guo</a></i></font></div>
        </div>

    </div>
</div>

pcrs/problems_java/templates/problems_java/grade_table.html
<div id="grade-code">
    <table id="gradeMatrix" class="pcrs-table">
        <tr class="pcrs-table-head-row">
            <td width="40%">Testcase</td>
            <td width="60%">Feedback</td>
            <td class="passed">Passed</td>
        </tr>
    </table>
</div>

pcrs/problems_java/templates/problems_java/problem_form.html
{% extends "problems/programming_problem_form.html" %}

{% block scripts %}
    {{ block.super }}
    {% load static %}
    {% include "problems_java/problem_form_scripts.html" %}
{% endblock %}

{% block related_items %}
{% endblock %}

pcrs/problems_java/templates/problems_java/problem_form_scripts.html
{% load compress %}
{% compress js %}
<script>
/**
 * Show a help dialog including some sample code for the instructor.
 */
function showJunitHelp() {
    var previewTcm = new TabbedCodeMirror();
    previewTcm.setNewFileOptions({
        'readOnly': true,
        'mode': cmModeForLanguageAndVersion('java', null),
        'theme': user_theme, // global
    });

    var sampleCode = $('#sampleJUnitSuiteCode').text().trim();
    previewTcm.addFile({
        'name': 'SampleSuite.java',
        'code': sampleCode,
    });
    AlertModal.alert('Sample Test Suite', previewTcm.getJQueryObject());
    previewTcm.refresh();
}

problemFormPageLoadCallback = function() {
    var handler = new JavaProblemFormHandler($('form'));
    handler.pageLoad();

    $('#div_id_test_suite label').append(
        $('<a type="button"></a>')
            .attr('title', 'Test Suite Help')
            .attr('class', 'label-icon-button')
            .click(showJunitHelp)
            .append('<i class="question-sign-icon"></i>'));
    $('#div_id_solution label').append(
        $('<a type="button"></a>')
            .attr('title', 'Solution Help')
            .attr('class', 'label-icon-button')
            .click(function() {
                AlertModal.alert('Solution Help',
                    'Your solution student_code tags and file names must '
                    + 'match the starter code to use the "Load Solution" '
                    + 'button on the instructor submission test page.'
                    + 'In general, the solution code is used for instructor '
                    + 'reference, so it is completely optional.');
            })
            .append('<i class="question-sign-icon"></i>'));
}

function JavaProblemFormHandler($form) {
    var mode = cmModeForLanguageAndVersion('java', null);
    ProgrammingProblemFormHandler.call(this, $form, mode);
    this.enableTabsInStarterCode('java');

    // These are created in _setupCodeMirrors
    this.testSuiteCodeMirror = null;
    this.visualizerCodeMirror = null;
}
JavaProblemFormHandler.prototype =
    Object.create(ProgrammingProblemFormHandler.prototype);
JavaProblemFormHandler.prototype.constructor = JavaProblemFormHandler;

/**
 * @override
 */
JavaProblemFormHandler.prototype._setupCodeMirrors = function() {
    ProgrammingProblemFormHandler.prototype._setupCodeMirrors.call(this);
    this.testSuiteCodeMirror = to_code_mirror('java', null,
        $('#id_test_suite'), $('#id_test_suite').text(), false);
    this.visualizerCodeMirror = to_code_mirror('java', null,
        $('#id_visualizer_code'), $('#id_visualizer_code').text(), false);
}

/**
 * @override
 */
JavaProblemFormHandler.prototype._setHiddenFieldValues = function() {
    var starterCode = TagManager.concatFilesIntoCode(
        this.starterCodeTcm.getFiles(), true);
    var solutionCode = TagManager.concatFilesIntoCode(
        this.solutionTcm.getFiles(), true);
    var testSuiteCode = this.testSuiteCodeMirror.getValue();
    var visualizerCode = this.visualizerCodeMirror.getValue();

    this.$form.find("#id_starter_code_tmp").val(starterCode);
    this.$form.find("#id_solution_tmp").val(solutionCode);
    this.$form.find("#id_test_suite_tmp").val(testSuiteCode);
    this.$form.find("#id_visualizer_code_tmp").val(visualizerCode);
}

/**
  * @override
  */
JavaProblemFormHandler.prototype._createHiddenFormFields = function() {
    ProgrammingProblemFormHandler.prototype._createHiddenFormFields.call(this);
    this.$form.append(this._createHiddenField('test_suite'));
    this.$form.append(this._createHiddenField('visualizer_code'));
}
</script>
{% endcompress %}

<script id="sampleJUnitSuiteCode" type="text/plain">
import org.junit.*;
import static org.junit.Assert.*;
import java.io.PrintStream;
import java.io.ByteArrayOutputStream;

public class Tests {
    private java.util.List list;
    private ByteArrayOutputStream out;
    private PrintStream oldSystemOut;

    // Called before every test case.
    @Before
    public void setUp() {
        list = new java.util.ArrayList();
        // Used to capture stdout - handy for testing
        out = new ByteArrayOutputStream();
        oldSystemOut = System.out;
        System.setOut(new PrintStream(out));
    }

    // Called after every test case. Used to clean up resources.
    @After
    public void tearDown() {
        System.setOut(oldSystemOut);
        // Dump stdout - we still want it to print eventually
        System.out.println(out.toString());
        list = null;
        out = null;
    }

    /**
     * Test case comments will be shown to the student when they submit code.
     * You can either have them as a block comment or a line comment above
     * each test case.
     */
    @Test
    public void testFoo() {
        // Not providing an assert description will hide the assertion details.
        assertEquals(4, 2 + 2);
        // If you provide a description, the assert will _not_ be hidden.
        assertEquals("Arithmetic is broken!", 6, 3 + 3);
    }

    @Test(expected=IndexOutOfBoundsException.class)
    public void testIndexException() {
        Object o = list.get(42);
    }

    @Test
    public void testCaptureStdout() {
        System.out.println("o hai");
        assertEquals("o hai\n", out.toString());
    }
}
</script>

pcrs/problems_java/templates/problems_java/submission.html
{% extends "problems/submission.html" %}

{% load static %}
{% block scripts %}
    {{ block.super }}
    {% load static %}
    {% include "problems/code_problem_scripts.html" %}
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    {% include "problems/code_problem_stylesheets.html" %}
{% endblock %}

{% block page_title %}
{% endblock %}

{% block content %}

    <div id="{{ problem.get_problem_type_name }}-{{ problem.pk }}" class="code-mirror-wrapper">
        {% include "problems_java/submission_widget.html" %}
    </div>

{% endblock %}

pcrs/problems_java/templates/problems_java/submission_widget.html
{% extends "problems/submission_widget.html" %}

{% block problem_specific %}
    {% include "problems_java/grade_table.html" %}
    {% include "problems/wait_async_job.html" %}
{% endblock %}